# base image
FROM node:9.6.1

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm install
RUN npm install create-react-app -g

# start app
CMD ["npm", "start"]

# Build with =>  docker build -t first-docker-todo-app -f Dockerfile_dev
# Run with `docker run -v ${PWD}:/usr/src/app -v /usr/src/app/node_modules  -p 3000:3000  --rm  first-docker-todo-app`